In [1]:
import os
os.getcwd()

'C:\\Users\\SOWMYA\\Desktop\\remote internship 2020\\python codes'

In [2]:
os.chdir("C:/Users/SOWMYA/Desktop/remote internship 2020/datasets")
os.getcwd()


'C:\\Users\\SOWMYA\\Desktop\\remote internship 2020\\datasets'

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import preprocessing 
import statsmodels.formula.api as smf

In [4]:
cars = pd.read_csv("auto-mpg.csv")

In [5]:
cars

%mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0  3504.0          12.0   
1    15.0          8         350.0       165.0  3693.0          11.5   
2    18.0          8         318.0       150.0  3436.0          11.0   
3    16.0          8         304.0       150.0  3433.0          12.0   
4    17.0          8         302.0       140.0  3449.0          10.5   
5    15.0          8         429.0       198.0  4341.0          10.0   
6    14.0          8         454.0       220.0  4354.0           9.0   
7    14.0          8         440.0       215.0  4312.0           8.5   
8    14.0          8         455.0       225.0  4425.0          10.0   
9    15.0          8         390.0       190.0  3850.0           8.5   
10   15.0          8         383.0       170.0  3563.0          10.0   
11   14.0          8         340.0       160.0  3609.0           8.0   
12   15.0          8         400.0       150.0  3761.0           9.5   
13   14.0          8         455.0       225.0  3086.0          10.0   
14   24.0          4         113.0        95.0  2372.0          15.0   
15   22.0          6         198.0        95.0  2833.0          15.5   
16   18.0          6         199.0        97.0  2774.0          15.5   
17   21.0          6         200.0        85.0  2587.0          16.0   
18   27.0          4          97.0        88.0  2130.0          14.5   
19   26.0          4          97.0        46.0  1835.0          20.5   
20   25.0          4         110.0        87.0  2672.0          17.5   
21   24.0          4         107.0        90.0  2430.0          14.5   
22   25.0          4         104.0        95.0  2375.0          17.5   
23   26.0          4         121.0       113.0  2234.0          12.5   
24   21.0          6         199.0        90.0  2648.0          15.0   
25   10.0          8         360.0       215.0  4615.0          14.0   
26   10.0          8         307.0       200.0  4376.0          15.0   
27   11.0          8         318.0       210.0  4382.0          13.5   
28    9.0          8         304.0       193.0  4732.0          18.5   
29   27.0          4          97.0        88.0  2130.0          14.5   
..    ...        ...           ...         ...     ...           ...   
368  27.0          4         112.0        88.0  2640.0          18.6   
369  34.0          4         112.0        88.0  2395.0          18.0   
370  31.0          4         112.0        85.0  2575.0          16.2   
371  29.0          4         135.0        84.0  2525.0          16.0   
372  27.0          4         151.0        90.0  2735.0          18.0   
373  24.0          4         140.0        92.0  2865.0          16.4   
374  23.0          4         151.0         NaN     NaN        3035.0   
375  36.0          4         105.0        74.0  1980.0          15.3   
376  37.0          4          91.0        68.0  2025.0          18.2   
377  31.0          4          91.0        68.0  1970.0          17.6   
378  38.0          4         105.0        63.0  2125.0          14.7   
379  36.0          4          98.0        70.0  2125.0          17.3   
380  36.0          4         120.0        88.0  2160.0          14.5   
381  36.0          4         107.0        75.0  2205.0          14.5   
382  34.0          4         108.0        70.0  2245.0          16.9   
383  38.0          4          91.0        67.0  1965.0          15.0   
384  32.0          4          91.0        67.0  1965.0          15.7   
385  38.0          4          91.0        67.0  1995.0          16.2   
386  25.0          6         181.0       110.0  2945.0          16.4   
387  38.0          6         262.0        85.0  3015.0          17.0   
388  26.0          4         156.0        92.0  2585.0          14.5   
389  22.0          6         232.0       112.0  2835.0          14.7   
390  32.0          4         144.0        96.0  2665.0          13.9   
391  36.0          4         135.0        84.

In [7]:
x=cars.iloc[:,1:9].values
x

array([[8, 307.0, 130.0, ..., 70.0, 1, 'chevrolet chevelle malibu'],
       [8, 350.0, 165.0, ..., 70.0, 1, 'buick skylark 320'],
       [8, 318.0, 150.0, ..., 70.0, 1, 'plymouth satellite'],
       ...,
       [4, 135.0, 84.0, ..., 82.0, 1, 'dodge rampage'],
       [4, 120.0, 79.0, ..., 82.0, 1, 'ford ranger'],
       [4, 119.0, 82.0, ..., 82.0, 1, 'chevy s-10']], dtype=object)

In [8]:
y=cars.iloc[:,0].values
y

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

In [10]:
from sklearn.model_selection import train_test_split  #train_test_split splits arrays or matrices into random train and test subsets. 
X_train, X_test, y_train, y_test = train_test_split(x, y,test_size=0.4,random_state =1) 

In [11]:
X_train

array([[8, 305.0, 130.0, ..., 79.0, 1, 'chevrolet caprice classic'],
       [4, 91.0, 68.0, ..., 82.0, 3, 'mazda glc custom'],
       [4, 83.0, 61.0, ..., 74.0, 3, 'datsun 710'],
       ...,
       [8, 304.0, 150.0, ..., 72.0, 1, 'amc matador (sw)'],
       [4, 97.0, 75.0, ..., 77.0, 3, 'toyota corolla liftback'],
       [6, 232.0, 100.0, ..., 71.0, 1, 'amc matador']], dtype=object)

In [12]:
y_train

array([17. , 31. , 32. , 27. , 12. , 17. , 16. , 29.8, 36. , 17.5, 36. ,
       44.6, 20.6, 22. , 24. , 36.1, 18. , 16. , 22. , 29. , 43.1, 18. ,
       24. , 15. , 26. , 26. , 16. , 23.8, 13. , 21.1, 28. , 36.1, 20. ,
       39. , 20. , 26. , 38. , 27. , 14. , 13. , 18. , 37. , 30. , 31. ,
        9. , 25. , 27. , 19. , 25. , 23.9, 18. , 40.9, 20.5, 32.2, 19. ,
       31.5, 17. , 34. , 14. , 15. , 15. , 22. , 18.6, 17. , 44. , 32. ,
       15.5, 36. , 22. , 46.6, 18. , 26.5, 23. , 36. , 19. , 21. , 23. ,
       25.5, 37.3, 14. , 24. , 23. , 21. , 12. , 31. , 20. , 17. , 13. ,
       21. , 40.8, 17.5, 25. , 28. , 16. , 34.2, 16. , 16.5, 25.4, 30. ,
       22.4, 15.5, 30. , 26. , 26.4, 31.9, 19.2, 33. , 18. , 26. , 24. ,
       23.9, 23. , 35.1, 35. , 19. , 22.5, 33. , 28. , 43.4, 11. , 33.5,
       26. , 16.9, 20. , 13. , 24. , 14. , 26. , 17.5, 19. , 44.3, 15. ,
       30.9, 13. , 19. , 30.5, 24. , 28.4, 19. , 31.6, 25. , 23. , 14. ,
       18. , 22. , 17.7, 27. , 24. , 34.4, 18. , 30