# Taking care of Missing Data

In [1]:
import os
os.chdir("C:/Users/Abhi Matlapudi/Desktop/ML-Project Cars")

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import preprocessing 
import statsmodels.formula.api as smf

In [3]:
cars = pd.read_csv("auto-mpg.csv")

In [4]:
cars

%mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130  3504.0          12.0   
1    15.0          8         350.0        165  3693.0          11.5   
2    18.0          8         318.0        150  3436.0          11.0   
3    16.0          8         304.0        150  3433.0          12.0   
4    17.0          8         302.0        140  3449.0          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86  2790.0          15.6   
394  44.0          4          97.0         52  2130.0          24.6   
395  32.0          4         135.0         84  2295.0          11.6   
396  28.0          4         120.0         79  2625.0          18.6   
397  31.0          4         119.0         82  2720.0          19.4   

     model year  origin                   car name  \
0          70.0       1  chevrolet chevelle malibu   
1          70.0       1          buick skylark 320   
2          70.0       1         plymouth satellite   
3          70.0       1              amc rebel sst   
4          70.0       1                ford torino   
..          ...     ...                        ...   
393        82.0       1            ford mustang gl   
394        82.0       2                  vw pickup   
395        82.0       1              dodge rampage   
396        82.0       1                ford ranger   
397        82.0       1                 chevy s-10   

                Engine Fuel Type  
0    premium unleaded (required)  
1    premium unleaded (required)  
2    premium unleaded (required)  
3    premium unleaded (required)  
4    premium unleaded (required)  
..                           ...  
393             regular unleaded  
394             regular unleaded  
395             regular unleaded  
396             regular unleaded  
397             regular unleaded  

[398 rows x 10 columns]

In [5]:
cars.isnull().any()

%mpg                False
cylinders           False
displacement        False
horsepower          False
weight               True
acceleration        False
model year          False
origin              False
car name            False
Engine Fuel Type    False
dtype: bool

In [6]:
cars['horsepower']=cars['horsepower'].replace('?',np.nan)

In [7]:
cars['horsepower'].isnull().sum()

6

In [8]:
cars['horsepower']=cars['horsepower'].astype('float64')

In [9]:
mean_hp=cars['horsepower'].mean()

In [10]:
cars['horsepower'].fillna(mean_hp,inplace=True)

In [11]:
mean_weight = cars['weight'].mean()

In [12]:
mean_weight

2977.5841836734694

In [13]:
cars['weight'].fillna(mean_weight,inplace=True)

In [14]:
cars.isnull().sum()

%mpg                0
cylinders           0
displacement        0
horsepower          0
weight              0
acceleration        0
model year          0
origin              0
car name            0
Engine Fuel Type    0
dtype: int64

In [19]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()
cars['Engine Fuel Type']=labelencoder_y.fit_transform(cars['Engine Fuel Type'])

In [20]:
cars=cars.drop('car name',axis=1)

# Outliers

In [21]:
from scipy import stats
import numpy as np
z = np.abs(stats.zscore(cars))
print(z)

[[0.7064387  1.49819126 1.0906037  ... 0.63447853 0.18468921 0.23688156]
 [1.09075062 1.49819126 1.5035143  ... 0.63447853 0.18468921 0.23688156]
 [0.7064387  1.49819126 1.19623199 ... 0.63447853 0.18468921 0.23688156]
 ...
 [1.08701694 0.85632057 0.56103873 ... 0.85981086 0.18468921 0.68742099]
 [0.57460104 0.85632057 0.70507731 ... 0.85981086 0.18468921 0.68742099]
 [0.95891297 0.85632057 0.71467988 ... 0.85981086 0.18468921 0.68742099]]


In [22]:
threshold = 3
print(np.where(z > 3))

(array([  6,   8,  13,  32,  32,  32,  95, 116, 126, 126, 126, 135, 140,
       142, 144, 146, 153, 159, 161, 164, 174, 175, 182, 187, 190, 256,
       257, 258, 259, 330, 330, 330, 336, 336, 336, 354, 354, 354, 374,
       374, 374], dtype=int64), array([3, 3, 3, 5, 6, 7, 3, 3, 5, 6, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 5, 6, 7, 5, 6, 7, 5, 6, 7, 5, 6, 7],
      dtype=int64))


In [23]:
print(z[6][3])

3.0282326205181938


In [24]:
Q1 = cars.quantile(0.25)
Q3 = cars.quantile(0.75)
IQR = Q3 - Q1
print(IQR)

%mpg                  11.500
cylinders              4.000
displacement         157.750
horsepower            49.000
weight              1379.500
acceleration           3.475
model year             6.000
origin                 1.000
Engine Fuel Type       1.000
dtype: float64


In [25]:
print(cars < (Q1 - 1.5 * IQR)) |(cars > (Q3 + 1.5 * IQR))

      %mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    False      False         False       False   False         False   
1    False      False         False       False   False         False   
2    False      False         False       False   False         False   
3    False      False         False       False   False         False   
4    False      False         False       False   False         False   
..     ...        ...           ...         ...     ...           ...   
393  False      False         False       False   False         False   
394  False      False         False       False   False         False   
395  False      False         False       False   False         False   
396  False      False         False       False   False         False   
397  False      False         False       False   False         False   

     model year  origin  Engine Fuel Type  
0         False   False             False  
1         False   False            

TypeError: cannot compare a dtyped [bool] array with a scalar of type [NoneType]

In [26]:
cars_o = cars[(z < 3).all(axis=1)]

In [27]:
cars_o

%mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0  3504.0          12.0   
1    15.0          8         350.0       165.0  3693.0          11.5   
2    18.0          8         318.0       150.0  3436.0          11.0   
3    16.0          8         304.0       150.0  3433.0          12.0   
4    17.0          8         302.0       140.0  3449.0          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0  2790.0          15.6   
394  44.0          4          97.0        52.0  2130.0          24.6   
395  32.0          4         135.0        84.0  2295.0          11.6   
396  28.0          4         120.0        79.0  2625.0          18.6   
397  31.0          4         119.0        82.0  2720.0          19.4   

     model year  origin  Engine Fuel Type  
0          70.0       1                 3  
1          70.0       1                 3  
2          70.0       1                 3  
3          70.0       1                 3  
4          70.0       1                 3  
..          ...     ...               ...  
393        82.0       1                 4  
394        82.0       2                 4  
395        82.0       1                 4  
396        82.0       1                 4  
397        82.0       1                 4  

[369 rows x 9 columns]

In [28]:
cars.shape

(398, 9)

In [29]:
cars_o.shape

(369, 9)

In [30]:
cars_out = cars[~((cars < (Q1 - 1.5 * IQR)) |(cars > (Q3 + 1.5 * IQR))).any(axis=1)]
cars_out.shape

(334, 9)